{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PySWMM - Python API to SWMM"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This notebook demonstrates the basic capability provided by the PySWMM API to EPA SWMM. The basic example uses a simple tutorial model developed in PCSWMM, contained for present purposes in the `pcswmm_ex01/example01.inp` file. The PySWMM API can be used in conjuction with professional grade model development applications like PCSWMM to enable programmatic control of stormwater collection system models."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Outline\n",
    "The basic functionalities demonstrated in this notebook include programmatic manipulation of the previously created SWMM model to:\n",
    "\n",
    "-  Read model output (from PCSWMM runs) in Jupyter\n",
    "-  Write changes to model input files from Jupyter\n",
    "-  Run the SWMM model programatically from Jupyter\n",
    "-  Generate simple interactive graphics summarizing impacts of changes"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Read model output from prior runs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# viz imports\n",
    "import plotly.graph_objects as go \n",
    "from dash import Dash\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "from dash.dependencies import Input, Output\n",
    "# quant imports\n",
    "import pyswmm\n",
    "import swmmio\n",
    "from swmm.toolkit.shared_enum import NodeAttribute\n",
    "import random\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x292fedd2a10>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "... SWMM Version 5.2.4\n",
      "... Run Complete"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\plotly\\graph_objs\\_deprecations.py:378: DeprecationWarning:\n",
      "\n",
      "plotly.graph_objs.Line is deprecated.\n",
      "Please replace it with one of the following more specific types\n",
      "  - plotly.graph_objs.scatter.Line\n",
      "  - plotly.graph_objs.layout.shape.Line\n",
      "  - etc.\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "... SWMM Version 5.2.4\n",
      "... Run Complete"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\plotly\\graph_objs\\_deprecations.py:378: DeprecationWarning:\n",
      "\n",
      "plotly.graph_objs.Line is deprecated.\n",
      "Please replace it with one of the following more specific types\n",
      "  - plotly.graph_objs.scatter.Line\n",
      "  - plotly.graph_objs.layout.shape.Line\n",
      "  - etc.\n",
      "\n",
      "\n",
      "[2023-12-01 15:29:05,866] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\gcoyle\\AppData\\Local\\Temp\\ipykernel_116480\\3518104875.py\", line 26, in update_rain\n",
      "    baseline.inp.save(newfp)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\core.py\", line 674, in save\n",
      "    replace_inp_section(target_path, section, data)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\utils\\modify_model.py\", line 59, in replace_inp_section\n",
      "    os.remove(inp_path)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pcswmm_ex01/example2.inp'\n",
      "[2023-12-01 15:29:07,114] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\gcoyle\\AppData\\Local\\Temp\\ipykernel_116480\\3518104875.py\", line 26, in update_rain\n",
      "    baseline.inp.save(newfp)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\core.py\", line 674, in save\n",
      "    replace_inp_section(target_path, section, data)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\utils\\modify_model.py\", line 59, in replace_inp_section\n",
      "    os.remove(inp_path)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pcswmm_ex01/example2.inp'\n",
      "[2023-12-01 15:29:07,175] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\gcoyle\\AppData\\Local\\Temp\\ipykernel_116480\\3518104875.py\", line 26, in update_rain\n",
      "    baseline.inp.save(newfp)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\core.py\", line 674, in save\n",
      "    replace_inp_section(target_path, section, data)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\utils\\modify_model.py\", line 59, in replace_inp_section\n",
      "    os.remove(inp_path)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pcswmm_ex01/example2.inp'\n",
      "[2023-12-01 15:29:07,177] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\gcoyle\\AppData\\Local\\Temp\\ipykernel_116480\\3518104875.py\", line 26, in update_rain\n",
      "    baseline.inp.save(newfp)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\core.py\", line 674, in save\n",
      "    replace_inp_section(target_path, section, data)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\utils\\modify_model.py\", line 59, in replace_inp_section\n",
      "    os.remove(inp_path)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pcswmm_ex01/example2.inp'\n",
      "[2023-12-01 15:29:07,199] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\flask\\app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\dash\\_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\gcoyle\\AppData\\Local\\Temp\\ipykernel_116480\\3518104875.py\", line 26, in update_rain\n",
      "    baseline.inp.save(newfp)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\core.py\", line 674, in save\n",
      "    replace_inp_section(target_path, section, data)\n",
      "  File \"c:\\temp\\swmm-dash-mlflow\\.venv\\Lib\\site-packages\\swmmio\\utils\\modify_model.py\", line 59, in replace_inp_section\n",
      "    os.remove(inp_path)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pcswmm_ex01/example2.inp'\n"
     ]
    }
   ],
   "source": [
    "# Build App\n",
    "app = Dash(__name__)\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"SWMM Model Updating\"),\n",
    "    dcc.Graph(id='graph'),\n",
    "    html.Button(id='rain-button', n_clicks=0, children='New Rainfall')\n",
    "])\n",
    "    \n",
    "# Define callback to update graph\n",
    "@app.callback(\n",
    "    Output('graph', 'figure'),\n",
    "    Input('rain-button','n_clicks')\n",
    ")\n",
    "def update_rain(n_clicks, file_cnt=2):\n",
    "    # get current model rainfall\n",
    "    baseline = swmmio.Model('swmm_files/example1.inp')\n",
    "    rain = baseline.inp.timeseries.Value.values\n",
    "\n",
    "    # induce noise\n",
    "    new_rain = np.array([random.expovariate(0.5)*float(i) for i in rain])\n",
    "    baseline.inp.timeseries.Value = new_rain\n",
    "    # save back to new model input file\n",
    "    basepath = 'pcswmm_ex01/example'\n",
    "    filext = '.inp'\n",
    "    newfp = basepath + str(n_clicks+2) + filext\n",
    "    baseline.inp.save(newfp)\n",
    "    # construct name for new output file\n",
    "    newop = basepath+str(n_clicks+2)+'.out'\n",
    "    # execute new simulation\n",
    "    with pyswmm.Simulation(newfp) as sim:\n",
    "        sim.execute()\n",
    "    # return updated figure from new output file\n",
    "    return update_figure(newop)\n",
    "\n",
    "def update_figure(newop):\n",
    "    # read original model output\n",
    "    with pyswmm.Output('pcswmm_ex01/example1.out') as out:\n",
    "        ts0 = pd.Series(out.node_series(\n",
    "            'OF1',\n",
    "            NodeAttribute.INVERT_DEPTH\n",
    "        ))\n",
    "\n",
    "    # read new model output\n",
    "    with pyswmm.Output(newop) as out:\n",
    "        ts1 = pd.Series(out.node_series(\n",
    "            'OF1',\n",
    "            NodeAttribute.INVERT_DEPTH\n",
    "        ))\n",
    "\n",
    "    # Create figure\n",
    "    fig = go.Figure()\n",
    "    fig.update_layout(title_text=\"Depth of Flow at OF1\")\n",
    "    fig.add_trace(go.Line(x=ts0.index,y=ts0.values,\n",
    "                        mode='lines',\n",
    "                        name='original'))\n",
    "    fig.add_trace(go.Line(x=ts1.index,y=ts1.values,\n",
    "                        mode='lines',\n",
    "                        name=newop))\n",
    "    fig.update_layout(transition_duration=100)\n",
    "    return fig\n",
    "\n",
    "# Run app and display result inline in the notebook\n",
    "app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "ee5025e99464a60b759f0a095b20cb3e19f453cee6892c18b2061764e9e882c1"
  },
  "kernelspec": {
   "display_name": "Python 3.9.15 ('pyswmm39')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
